package mx.com.convenios.bean;
// Generated Apr 19, 2021, 12:37:22 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import org.apache.struts.action.ActionForm;

/**
 * CatEmpresa generated by hbm2java
 */
public class CatEmpresa extends ActionForm  implements java.io.Serializable {

	private int idEmpresa;
	private String nombre;
	private String nombreRepresentante;
	private String direccion;
	private String telefono;
	private String correo;
	private Set<CatSubEmpresa> catSubEmpresas = new HashSet<CatSubEmpresa>(0);
	private Set<HistoricoEmpresa> historicoEmpresas = new HashSet<HistoricoEmpresa>(0);
	private Set<CampanaConvenio> campanaConvenios = new HashSet<CampanaConvenio>(0);

	public CatEmpresa() {
	}

	public CatEmpresa(int idEmpresa, String nombre, String nombreRepresentante, String direccion, String telefono,
			String correo) {
		this.idEmpresa = idEmpresa;
		this.nombre = nombre;
		this.nombreRepresentante = nombreRepresentante;
		this.direccion = direccion;
		this.telefono = telefono;
		this.correo = correo;
	}

	public CatEmpresa(int idEmpresa, String nombre, String nombreRepresentante, String direccion, String telefono,
			String correo, Set<CatSubEmpresa> catSubEmpresas, Set<HistoricoEmpresa> historicoEmpresas, Set<CampanaConvenio> campanaConvenios) {
		this.idEmpresa = idEmpresa;
		this.nombre = nombre;
		this.nombreRepresentante = nombreRepresentante;
		this.direccion = direccion;
		this.telefono = telefono;
		this.correo = correo;
		this.catSubEmpresas = catSubEmpresas;
		this.historicoEmpresas = historicoEmpresas;
		this.campanaConvenios = campanaConvenios;
	}

	public int getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(int idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getNombreRepresentante() {
		return this.nombreRepresentante;
	}

	public void setNombreRepresentante(String nombreRepresentante) {
		this.nombreRepresentante = nombreRepresentante;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public Set<CatSubEmpresa> getCatSubEmpresas() {
		return this.catSubEmpresas;
	}

	public void setCatSubEmpresas(Set<CatSubEmpresa> catSubEmpresas) {
		this.catSubEmpresas = catSubEmpresas;
	}

	public Set<HistoricoEmpresa> getHistoricoEmpresas() {
		return this.historicoEmpresas;
	}

	public void setHistoricoEmpresas(Set<HistoricoEmpresa> historicoEmpresas) {
		this.historicoEmpresas = historicoEmpresas;
	}

	public Set<CampanaConvenio> getCampanaConvenios() {
		return this.campanaConvenios;
	}

	public void setCampanaConvenios(Set<CampanaConvenio> campanaConvenios) {
		this.campanaConvenios = campanaConvenios;
	}

}
