package mx.com.convenios.bean;

import java.sql.Timestamp;

// Generated Apr 19, 2021, 12:37:22 PM by Hibernate Tools 4.3.5.Final

/**
 * HistoricoEmpresa generated by hbm2java
 */
public class HistoricoEmpresa implements java.io.Serializable {

	private int idHistoricoEmpresa;
	private CatEmpresa catEmpresa;
	private int idEmpleado;
	private Timestamp fecha;

	public HistoricoEmpresa() {
	}

	public HistoricoEmpresa(int idHistoricoEmpresa, CatEmpresa catEmpresa, int idEmpleado, Timestamp fecha) {
		this.idHistoricoEmpresa = idHistoricoEmpresa;
		this.catEmpresa = catEmpresa;
		this.idEmpleado = idEmpleado;
		this.fecha = fecha;
	}

	public int getIdHistoricoEmpresa() {
		return this.idHistoricoEmpresa;
	}

	public void setIdHistoricoEmpresa(int idHistoricoEmpresa) {
		this.idHistoricoEmpresa = idHistoricoEmpresa;
	}

	public CatEmpresa getCatEmpresa() {
		return this.catEmpresa;
	}

	public void setCatEmpresa(CatEmpresa catEmpresa) {
		this.catEmpresa = catEmpresa;
	}

	public int getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado(int idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	public Timestamp getFecha() {
		return this.fecha;
	}

	public void setFecha(Timestamp fecha) {
		this.fecha = fecha;
	}

}
